version: "3"

services:
  fastapi:
    build: fastapi/
    ports:
      - 8000:8000
    networks:
      - deploy_network
    volumes:
      - .:/code
    container_name: fastapi
    image: nlp-app-fastapi:fastapi

  streamlit:
    build: streamlit/
    depends_on:
      - fastapi
    ports:
      - 8501:8501
    networks:
      - deploy_network
    volumes:
      - .:/code
    container_name: streamlit
    image: nlp-app-streamlit:streamlit

networks:
  deploy_network:
    driver: bridge
